# Tell Netlify to use the 21yunbox plugin
[[plugins]]
  package = "@21yunbox/netlify-plugin-21yunbox-deploy-to-china-cdn"

[[edge_functions]]
  path = "/lark-api/*"
  function = "cors"

[[edge_functions]]
  path = "/api/cloud-sync"
  function = "cloud-sync"

[[edge_functions]]
  path = "/api/lark-license"
  function = "lark-license"

[[redirects]]
  from = "/lark-api/*"
  to = "https://open.larksuite.com/:splat"
  status = 200
  force = true